//
//  ImageLoader.swift
//  ShuiHuCards
//
//  Created by 迪远 王 on 2018/12/8.
//  Copyright © 2018 andforce. All rights reserved.
//

import UIKit
import Foundation

struct ImageLoader {

    static let frontImagePaths: [String] = {
        var someStrs = [String]()

        someStrs.append(Bundle.main.path(forResource: "001-天魁星-呼保义-宋江", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "002-天罡星-玉麒麟-卢俊义", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "003-天机星-智多星-吴用", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "004-天闲星-入云龙-公孙胜", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "005-天勇星-大刀-关胜", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "006-天雄星-豹子头-林冲", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "007-天猛星-霹雳火-秦明", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "008-天威星-双鞭-呼延灼", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "009-天英星-小李广-花荣", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "010-天贵星-小旋风-柴进", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "011-天富星-扑天雕-李应", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "012-天满星-美髯公-朱仝", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "013-天孤星-花和尚-鲁智深", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "014-天伤星-行者-武松", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "015-天立星-双枪将-董平", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "016-天捷星-没羽箭-张清", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "017-天暗星-青面兽-杨志", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "018-天佑星-金枪手-徐宁", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "019-天空星-急先锋-索超", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "020-天速星-神行太保-戴宗", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "021-天异星-赤发鬼-刘唐", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "022-天杀星-黑旋风-李逵", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "023-天微星-九纹龙-史进", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "024-天究星-没遮拦-穆弘", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "025-天退星-插翅虎-雷横", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "026-天寿星-混江龙-李俊", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "027-天剑星-立地太岁-阮小二", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "028-天平星-船火儿-张横", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "029-天罪星-短命二郎-阮小五", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "030-天损星-浪里白条-张顺", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "031-天败星-活阎罗-阮小七", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "032-天牢星-病关索-杨雄", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "033-天慧星-拼命三郎-石秀", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "034-天暴星-两头蛇-解珍", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "035-天哭星-双尾蝎-解宝", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "036-天巧星-浪子-燕青", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "037-地魁星-神机军师-朱武", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "038-地煞星-镇三山-黄信", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "039-地勇星-病尉迟-孙立", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "040-地接星-丑郡马-宣赞", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "041-地雄星-井木犴-郝思文", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "042-地威星-百胜将-韩滔", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "043-地英星-天目将-彭玘", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "044-地奇星-圣水将军-单廷珪", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "045-地猛星-神火将军-魏定国", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "046-地文星-圣手书生-萧让", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "047-地正星-铁面孔目-裴宣", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "048-地阔星-摩云金翅-欧鹏", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "049-地斗星-火眼狻猊-邓飞", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "050-地强星-锦毛虎-燕顺", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "051-地暗星-锦豹子-杨林", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "052-地轴星-轰天雷-凌振", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "053-地会星-神算子-蒋敬", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "054-地佐星-小温侯-吕方", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "055-地佑星-赛仁贵-郭盛", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "056-地灵星-神医-安道全", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "057-地兽星-紫髯伯-皇甫端", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "058-地微星-矮脚虎-王英", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "059-地急星-一丈青-扈三娘", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "060-地暴星-丧门神-鲍旭", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "061-地然星-混世魔王-樊瑞", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "062-地好星-毛头星-孔明", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "063-地狂星-独火星-孔亮", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "064-地飞星-八臂那吒-项充", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "065-地走星-飞天大圣-李衮", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "066-地巧星-玉臂将-金大坚", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "067-地明星-铁笛仙-马麟", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "068-地进星-出洞蛟-童威", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "069-地退星-翻江蜃-童猛", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "070-地满星-玉幡竿-孟康", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "071-地遂星-通臂猿-侯健", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "072-地周星-跳涧虎-陈达", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "073-地隐星-白花蛇-杨春", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "074-地异星-白面郎君-郑天寿", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "075-地理星-九尾龟-陶宗旺", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "076-地俊星-铁扇子-宋清", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "077-地乐星-铁叫子-乐和", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "078-地捷星-花项虎-龚旺", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "079-地速星-中箭虎-丁得孙", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "080-地镇星-小遮拦-穆春", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "081-地稽星-操刀鬼-曹正", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "082-地魔星-云里金刚-宋万", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "083-地妖星-摸着天-杜迁", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "084-地幽星-病大虫-薛永", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "085-地伏星-金眼彪-施恩", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "086-地僻星-打虎将-李忠", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "087-地空星-小霸王-周通", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "088-地孤星-金钱豹子-汤隆", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "089-地全星-鬼脸儿-杜兴", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "090-地短星-出林龙-邹渊", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "091-地角星-独角龙-邹润", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "092-地囚星-旱地忽律-朱贵", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "093-地藏星-笑面虎-朱富", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "094-地平星-铁胳膊-蔡福", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "095-地损星-一枝花-蔡庆", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "096-地奴星-催命判官-李立", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "097-地察星-青眼虎-李云", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "098-地恶星-没面目-焦挺", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "099-地丑星-石将军-石勇", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "100-地数星-小尉迟-孙新", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "101-地阴星-母大虫-顾大嫂", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "102-地刑星-菜园子-张青", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "103-地壮星-母夜叉-孙二娘", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "104-地劣星-活闪婆-王定六", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "105-地健星-险道神-郁保四", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "106-地耗星-白日鼠-白胜", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "107-地贼星-鼓上蚤-时迁", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "108-地狗星-金毛犬-段景住", ofType:"jpg")!)

        return someStrs
    }()

    static let frontImages: [UIImage] = {

        var someStrs: [String] = frontImagePaths

        var images: [UIImage] = [UIImage]()
        for item in someStrs {
            images.append(UIImage.init(contentsOfFile: item)!)
        }

        return images
    }()

    static let reverseImages: [UIImage] = {

        var someStrs: [String] = reverseImagePaths

        var images: [UIImage] = [UIImage]()
        for item in someStrs {
            images.append(UIImage.init(contentsOfFile: item)!)
        }

        return images
    }()

    static let reverseImagePaths: [String] = {

        var someStrs = [String]()

        someStrs.append(Bundle.main.path(forResource: "001-天魁星-呼保义-宋江_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "002-天罡星-玉麒麟-卢俊义_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "003-天机星-智多星-吴用_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "004-天闲星-入云龙-公孙胜_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "005-天勇星-大刀-关胜_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "006-天雄星-豹子头-林冲_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "007-天猛星-霹雳火-秦明_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "008-天威星-双鞭-呼延灼_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "009-天英星-小李广-花荣_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "010-天贵星-小旋风-柴进_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "011-天富星-扑天雕-李应_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "012-天满星-美髯公-朱仝_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "013-天孤星-花和尚-鲁智深_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "014-天伤星-行者-武松_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "015-天立星-双枪将-董平_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "016-天捷星-没羽箭-张清_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "017-天暗星-青面兽-杨志_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "018-天佑星-金枪手-徐宁_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "019-天空星-急先锋-索超_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "020-天速星-神行太保-戴宗_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "021-天异星-赤发鬼-刘唐_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "022-天杀星-黑旋风-李逵_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "023-天微星-九纹龙-史进_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "024-天究星-没遮拦-穆弘_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "025-天退星-插翅虎-雷横_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "026-天寿星-混江龙-李俊_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "027-天剑星-立地太岁-阮小二_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "028-天平星-船火儿-张横_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "029-天罪星-短命二郎-阮小五_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "030-天损星-浪里白条-张顺_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "031-天败星-活阎罗-阮小七_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "032-天牢星-病关索-杨雄_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "033-天慧星-拼命三郎-石秀_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "034-天暴星-两头蛇-解珍_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "035-天哭星-双尾蝎-解宝_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "036-天巧星-浪子-燕青_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "037-地魁星-神机军师-朱武_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "038-地煞星-镇三山-黄信_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "039-地勇星-病尉迟-孙立_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "040-地接星-丑郡马-宣赞_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "041-地雄星-井木犴-郝思文_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "042-地威星-百胜将-韩滔_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "043-地英星-天目将-彭玘_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "044-地奇星-圣水将军-单廷珪_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "045-地猛星-神火将军-魏定国_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "046-地文星-圣手书生-萧让_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "047-地正星-铁面孔目-裴宣_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "048-地阔星-摩云金翅-欧鹏_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "049-地斗星-火眼狻猊-邓飞_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "050-地强星-锦毛虎-燕顺_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "051-地暗星-锦豹子-杨林_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "052-地轴星-轰天雷-凌振_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "053-地会星-神算子-蒋敬_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "054-地佐星-小温侯-吕方_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "055-地佑星-赛仁贵-郭盛_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "056-地灵星-神医-安道全_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "057-地兽星-紫髯伯-皇甫端_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "058-地微星-矮脚虎-王英_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "059-地急星-一丈青-扈三娘_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "060-地暴星-丧门神-鲍旭_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "061-地然星-混世魔王-樊瑞_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "062-地好星-毛头星-孔明_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "063-地狂星-独火星-孔亮_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "064-地飞星-八臂那吒-项充_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "065-地走星-飞天大圣-李衮_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "066-地巧星-玉臂将-金大坚_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "067-地明星-铁笛仙-马麟_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "068-地进星-出洞蛟-童威_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "069-地退星-翻江蜃-童猛_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "070-地满星-玉幡竿-孟康_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "071-地遂星-通臂猿-侯健_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "072-地周星-跳涧虎-陈达_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "073-地隐星-白花蛇-杨春_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "074-地异星-白面郎君-郑天寿_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "075-地理星-九尾龟-陶宗旺_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "076-地俊星-铁扇子-宋清_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "077-地乐星-铁叫子-乐和_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "078-地捷星-花项虎-龚旺_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "079-地速星-中箭虎-丁得孙_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "080-地镇星-小遮拦-穆春_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "081-地稽星-操刀鬼-曹正_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "082-地魔星-云里金刚-宋万_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "083-地妖星-摸着天-杜迁_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "084-地幽星-病大虫-薛永_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "085-地伏星-金眼彪-施恩_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "086-地僻星-打虎将-李忠_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "087-地空星-小霸王-周通_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "088-地孤星-金钱豹子-汤隆_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "089-地全星-鬼脸儿-杜兴_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "090-地短星-出林龙-邹渊_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "091-地角星-独角龙-邹润_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "092-地囚星-旱地忽律-朱贵_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "093-地藏星-笑面虎-朱富_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "094-地平星-铁胳膊-蔡福_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "095-地损星-一枝花-蔡庆_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "096-地奴星-催命判官-李立_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "097-地察星-青眼虎-李云_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "098-地恶星-没面目-焦挺_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "099-地丑星-石将军-石勇_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "100-地数星-小尉迟-孙新_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "101-地阴星-母大虫-顾大嫂_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "102-地刑星-菜园子-张青_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "103-地壮星-母夜叉-孙二娘_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "104-地劣星-活闪婆-王定六_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "105-地健星-险道神-郁保四_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "106-地耗星-白日鼠-白胜_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "107-地贼星-鼓上蚤-时迁_背面", ofType:"jpg")!)
        someStrs.append(Bundle.main.path(forResource: "108-地狗星-金毛犬-段景住_背面", ofType:"jpg")!)
        return someStrs
    }()
}
