//
//  ImageLoader.swift
//  ShuiHuCards
//
//  Created by 迪远 王 on 2018/12/8.
//  Copyright © 2018 andforce. All rights reserved.
//

import UIKit
import Foundation
import Kingfisher

struct ImageLoader {

    struct LocalImageProvider: ImageDataProvider {
        var cacheKey: String { return letter }
        let letter: String

        init(userNameFirstLetter: String) {
            letter = userNameFirstLetter
        }

        func data(handler: @escaping (Result<Data, Error>) -> Void) {
            let letter = self.letter as String
            let image = UIImage(contentsOfFile: letter)
            let data:Data = image!.jpegData(compressionQuality: 1.0)!
            handler(.success(data))
        }
    }

    static let names: [String] = {
        var nameStrings = [String]()

        nameStrings.append("天魁星 呼保义·宋江")
        nameStrings.append("天罡星 玉麒麟·卢俊义")
        nameStrings.append("天机星 智多星·吴用")
        nameStrings.append("天闲星 入云龙·公孙胜")
        nameStrings.append("天勇星 大刀·关胜")
        nameStrings.append("天雄星 豹子头·林冲")
        nameStrings.append("天猛星 霹雳火·秦明")
        nameStrings.append("天威星 双鞭·呼延灼")
        nameStrings.append("天英星 小李广·花荣")
        nameStrings.append("天贵星 小旋风·柴进")
        nameStrings.append("天富星 扑天雕·李应")
        nameStrings.append("天满星 美髯公·朱仝")
        nameStrings.append("天孤星 花和尚·鲁智深")
        nameStrings.append("天伤星 行者·武松")
        nameStrings.append("天立星 双枪将·董平")
        nameStrings.append("天捷星 没羽箭·张清")
        nameStrings.append("天暗星 青面兽·杨志")
        nameStrings.append("天佑星 金枪手·徐宁")
        nameStrings.append("天空星 急先锋·索超")
        nameStrings.append("天速星 神行太保·戴宗")
        nameStrings.append("天异星 赤发鬼·刘唐")
        nameStrings.append("天杀星 黑旋风·李逵")
        nameStrings.append("天微星 九纹龙·史进")
        nameStrings.append("天究星 没遮拦·穆弘")
        nameStrings.append("天退星 插翅虎·雷横")
        nameStrings.append("天寿星 混江龙·李俊")
        nameStrings.append("天剑星 立地太岁·阮小二")
        nameStrings.append("天平星 船火儿·张横")
        nameStrings.append("天罪星 短命二郎·阮小五")
        nameStrings.append("天损星 浪里白条·张顺")
        nameStrings.append("天败星 活阎罗·阮小七")
        nameStrings.append("天牢星 病关索·杨雄")
        nameStrings.append("天慧星 拼命三郎·石秀")
        nameStrings.append("天暴星 两头蛇·解珍")
        nameStrings.append("天哭星 双尾蝎·解宝")
        nameStrings.append("天巧星 浪子·燕青")
        nameStrings.append("地魁星 神机军师·朱武")
        nameStrings.append("地煞星 镇三山·黄信")
        nameStrings.append("地勇星 病尉迟·孙立")
        nameStrings.append("地接星 丑郡马·宣赞")
        nameStrings.append("地雄星 井木犴·郝思文")
        nameStrings.append("地威星 百胜将·韩滔")
        nameStrings.append("地英星 天目将·彭玘")
        nameStrings.append("地奇星 圣水将军·单廷珪")
        nameStrings.append("地猛星 神火将军·魏定国")
        nameStrings.append("地文星 圣手书生·萧让")
        nameStrings.append("地正星 铁面孔目·裴宣")
        nameStrings.append("地阔星 摩云金翅·欧鹏")
        nameStrings.append("地斗星 火眼狻猊·邓飞")
        nameStrings.append("地强星 锦毛虎·燕顺")
        nameStrings.append("地暗星 锦豹子·杨林")
        nameStrings.append("地轴星 轰天雷·凌振")
        nameStrings.append("地会星 神算子·蒋敬")
        nameStrings.append("地佐星 小温侯·吕方")
        nameStrings.append("地佑星 赛仁贵·郭盛")
        nameStrings.append("地灵星 神医·安道全")
        nameStrings.append("地兽星 紫髯伯·皇甫端")
        nameStrings.append("地微星 矮脚虎·王英")
        nameStrings.append("地急星 一丈青·扈三娘")
        nameStrings.append("地暴星 丧门神·鲍旭")
        nameStrings.append("地然星 混世魔王·樊瑞")
        nameStrings.append("地好星 毛头星·孔明")
        nameStrings.append("地狂星 独火星·孔亮")
        nameStrings.append("地飞星 八臂那吒·项充")
        nameStrings.append("地走星 飞天大圣·李衮")
        nameStrings.append("地巧星 玉臂将·金大坚")
        nameStrings.append("地明星 铁笛仙·马麟")
        nameStrings.append("地进星 出洞蛟·童威")
        nameStrings.append("地退星 翻江蜃·童猛")
        nameStrings.append("地满星 玉幡竿·孟康")
        nameStrings.append("地遂星 通臂猿·侯健")
        nameStrings.append("地周星 跳涧虎·陈达")
        nameStrings.append("地隐星 白花蛇·杨春")
        nameStrings.append("地异星 白面郎君·郑天寿")
        nameStrings.append("地理星 九尾龟·陶宗旺")
        nameStrings.append("地俊星 铁扇子·宋清")
        nameStrings.append("地乐星 铁叫子·乐和")
        nameStrings.append("地捷星 花项虎·龚旺")
        nameStrings.append("地速星 中箭虎·丁得孙")
        nameStrings.append("地镇星 小遮拦·穆春")
        nameStrings.append("地稽星 操刀鬼·曹正")
        nameStrings.append("地魔星 云里金刚·宋万")
        nameStrings.append("地妖星 摸着天·杜迁")
        nameStrings.append("地幽星 病大虫·薛永")
        nameStrings.append("地伏星 金眼彪·施恩")
        nameStrings.append("地僻星 打虎将·李忠")
        nameStrings.append("地空星 小霸王·周通")
        nameStrings.append("地孤星 金钱豹子·汤隆")
        nameStrings.append("地全星 鬼脸儿·杜兴")
        nameStrings.append("地短星 出林龙·邹渊")
        nameStrings.append("地角星 独角龙·邹润")
        nameStrings.append("地囚星 旱地忽律·朱贵")
        nameStrings.append("地藏星 笑面虎·朱富")
        nameStrings.append("地平星 铁胳膊·蔡福")
        nameStrings.append("地损星 一枝花·蔡庆")
        nameStrings.append("地奴星 催命判官·李立")
        nameStrings.append("地察星 青眼虎·李云")
        nameStrings.append("地恶星 没面目·焦挺")
        nameStrings.append("地丑星 石将军·石勇")
        nameStrings.append("地数星 小尉迟·孙新")
        nameStrings.append("地阴星 母大虫·顾大嫂")
        nameStrings.append("地刑星 菜园子·张青")
        nameStrings.append("地壮星 母夜叉·孙二娘")
        nameStrings.append("地劣星 活闪婆·王定六")
        nameStrings.append("地健星 险道神·郁保四")
        nameStrings.append("地耗星 白日鼠·白胜")
        nameStrings.append("地贼星 鼓上蚤·时迁")
        nameStrings.append("地狗星 金毛犬·段景住")

        return nameStrings
    }()


    static let frontImagePaths: [String] = {
        var someStrs = [String]()

        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/001-天魁星-呼保义-宋江.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/002-天罡星-玉麒麟-卢俊义.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/003-天机星-智多星-吴用.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/004-天闲星-入云龙-公孙胜.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/005-天勇星-大刀-关胜.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/006-天雄星-豹子头-林冲.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/007-天猛星-霹雳火-秦明.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/008-天威星-双鞭-呼延灼.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/009-天英星-小李广-花荣.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/010-天贵星-小旋风-柴进.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/011-天富星-扑天雕-李应.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/012-天满星-美髯公-朱仝.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/013-天孤星-花和尚-鲁智深.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/014-天伤星-行者-武松.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/015-天立星-双枪将-董平.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/016-天捷星-没羽箭-张清.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/017-天暗星-青面兽-杨志.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/018-天佑星-金枪手-徐宁.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/019-天空星-急先锋-索超.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/020-天速星-神行太保-戴宗.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/021-天异星-赤发鬼-刘唐.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/022-天杀星-黑旋风-李逵.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/023-天微星-九纹龙-史进.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/024-天究星-没遮拦-穆弘.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/025-天退星-插翅虎-雷横.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/026-天寿星-混江龙-李俊.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/027-天剑星-立地太岁-阮小二.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/028-天平星-船火儿-张横.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/029-天罪星-短命二郎-阮小五.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/030-天损星-浪里白条-张顺.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/031-天败星-活阎罗-阮小七.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/032-天牢星-病关索-杨雄.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/033-天慧星-拼命三郎-石秀.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/034-天暴星-两头蛇-解珍.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/035-天哭星-双尾蝎-解宝.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/036-天巧星-浪子-燕青.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/037-地魁星-神机军师-朱武.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/038-地煞星-镇三山-黄信.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/039-地勇星-病尉迟-孙立.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/040-地接星-丑郡马-宣赞.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/041-地雄星-井木犴-郝思文.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/042-地威星-百胜将-韩滔.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/043-地英星-天目将-彭玘.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/044-地奇星-圣水将军-单廷珪.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/045-地猛星-神火将军-魏定国.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/046-地文星-圣手书生-萧让.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/047-地正星-铁面孔目-裴宣.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/048-地阔星-摩云金翅-欧鹏.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/049-地斗星-火眼狻猊-邓飞.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/050-地强星-锦毛虎-燕顺.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/051-地暗星-锦豹子-杨林.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/052-地轴星-轰天雷-凌振.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/053-地会星-神算子-蒋敬.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/054-地佐星-小温侯-吕方.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/055-地佑星-赛仁贵-郭盛.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/056-地灵星-神医-安道全.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/057-地兽星-紫髯伯-皇甫端.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/058-地微星-矮脚虎-王英.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/059-地急星-一丈青-扈三娘.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/060-地暴星-丧门神-鲍旭.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/061-地然星-混世魔王-樊瑞.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/062-地好星-毛头星-孔明.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/063-地狂星-独火星-孔亮.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/064-地飞星-八臂那吒-项充.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/065-地走星-飞天大圣-李衮.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/066-地巧星-玉臂将-金大坚.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/067-地明星-铁笛仙-马麟.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/068-地进星-出洞蛟-童威.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/069-地退星-翻江蜃-童猛.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/070-地满星-玉幡竿-孟康.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/071-地遂星-通臂猿-侯健.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/072-地周星-跳涧虎-陈达.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/073-地隐星-白花蛇-杨春.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/074-地异星-白面郎君-郑天寿.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/075-地理星-九尾龟-陶宗旺.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/076-地俊星-铁扇子-宋清.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/077-地乐星-铁叫子-乐和.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/078-地捷星-花项虎-龚旺.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/079-地速星-中箭虎-丁得孙.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/080-地镇星-小遮拦-穆春.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/081-地稽星-操刀鬼-曹正.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/082-地魔星-云里金刚-宋万.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/083-地妖星-摸着天-杜迁.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/084-地幽星-病大虫-薛永.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/085-地伏星-金眼彪-施恩.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/086-地僻星-打虎将-李忠.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/087-地空星-小霸王-周通.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/088-地孤星-金钱豹子-汤隆.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/089-地全星-鬼脸儿-杜兴.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/090-地短星-出林龙-邹渊.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/091-地角星-独角龙-邹润.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/092-地囚星-旱地忽律-朱贵.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/093-地藏星-笑面虎-朱富.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/094-地平星-铁胳膊-蔡福.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/095-地损星-一枝花-蔡庆.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/096-地奴星-催命判官-李立.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/097-地察星-青眼虎-李云.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/098-地恶星-没面目-焦挺.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/099-地丑星-石将军-石勇.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/100-地数星-小尉迟-孙新.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/101-地阴星-母大虫-顾大嫂.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/102-地刑星-菜园子-张青.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/103-地壮星-母夜叉-孙二娘.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/104-地劣星-活闪婆-王定六.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/105-地健星-险道神-郁保四.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/106-地耗星-白日鼠-白胜.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/107-地贼星-鼓上蚤-时迁.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/108-地狗星-金毛犬-段景住.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)

        return someStrs
    }()

    static let reverseImagePaths: [String] = {

        var someStrs = [String]()

        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/001-天魁星-呼保义-宋江_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/002-天罡星-玉麒麟-卢俊义_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/003-天机星-智多星-吴用_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/004-天闲星-入云龙-公孙胜_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/005-天勇星-大刀-关胜_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/006-天雄星-豹子头-林冲_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/007-天猛星-霹雳火-秦明_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/008-天威星-双鞭-呼延灼_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/009-天英星-小李广-花荣_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/010-天贵星-小旋风-柴进_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/011-天富星-扑天雕-李应_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/012-天满星-美髯公-朱仝_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/013-天孤星-花和尚-鲁智深_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/014-天伤星-行者-武松_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/015-天立星-双枪将-董平_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/016-天捷星-没羽箭-张清_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/017-天暗星-青面兽-杨志_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/018-天佑星-金枪手-徐宁_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/019-天空星-急先锋-索超_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/020-天速星-神行太保-戴宗_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/021-天异星-赤发鬼-刘唐_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/022-天杀星-黑旋风-李逵_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/023-天微星-九纹龙-史进_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/024-天究星-没遮拦-穆弘_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/025-天退星-插翅虎-雷横_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/026-天寿星-混江龙-李俊_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/027-天剑星-立地太岁-阮小二_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/028-天平星-船火儿-张横_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/029-天罪星-短命二郎-阮小五_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/030-天损星-浪里白条-张顺_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/031-天败星-活阎罗-阮小七_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/032-天牢星-病关索-杨雄_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/033-天慧星-拼命三郎-石秀_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/034-天暴星-两头蛇-解珍_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/035-天哭星-双尾蝎-解宝_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/036-天巧星-浪子-燕青_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/037-地魁星-神机军师-朱武_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/038-地煞星-镇三山-黄信_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/039-地勇星-病尉迟-孙立_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/040-地接星-丑郡马-宣赞_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/041-地雄星-井木犴-郝思文_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/042-地威星-百胜将-韩滔_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/043-地英星-天目将-彭玘_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/044-地奇星-圣水将军-单廷珪_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/045-地猛星-神火将军-魏定国_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/046-地文星-圣手书生-萧让_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/047-地正星-铁面孔目-裴宣_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/048-地阔星-摩云金翅-欧鹏_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/049-地斗星-火眼狻猊-邓飞_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/050-地强星-锦毛虎-燕顺_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/051-地暗星-锦豹子-杨林_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/052-地轴星-轰天雷-凌振_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/053-地会星-神算子-蒋敬_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/054-地佐星-小温侯-吕方_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/055-地佑星-赛仁贵-郭盛_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/056-地灵星-神医-安道全_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/057-地兽星-紫髯伯-皇甫端_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/058-地微星-矮脚虎-王英_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/059-地急星-一丈青-扈三娘_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/060-地暴星-丧门神-鲍旭_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/061-地然星-混世魔王-樊瑞_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/062-地好星-毛头星-孔明_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/063-地狂星-独火星-孔亮_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/064-地飞星-八臂那吒-项充_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/065-地走星-飞天大圣-李衮_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/066-地巧星-玉臂将-金大坚_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/067-地明星-铁笛仙-马麟_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/068-地进星-出洞蛟-童威_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/069-地退星-翻江蜃-童猛_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/070-地满星-玉幡竿-孟康_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/071-地遂星-通臂猿-侯健_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/072-地周星-跳涧虎-陈达_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/073-地隐星-白花蛇-杨春_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/074-地异星-白面郎君-郑天寿_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/075-地理星-九尾龟-陶宗旺_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/076-地俊星-铁扇子-宋清_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/077-地乐星-铁叫子-乐和_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/078-地捷星-花项虎-龚旺_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/079-地速星-中箭虎-丁得孙_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/080-地镇星-小遮拦-穆春_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/081-地稽星-操刀鬼-曹正_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/082-地魔星-云里金刚-宋万_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/083-地妖星-摸着天-杜迁_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/084-地幽星-病大虫-薛永_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/085-地伏星-金眼彪-施恩_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/086-地僻星-打虎将-李忠_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/087-地空星-小霸王-周通_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/088-地孤星-金钱豹子-汤隆_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/089-地全星-鬼脸儿-杜兴_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/090-地短星-出林龙-邹渊_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/091-地角星-独角龙-邹润_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/092-地囚星-旱地忽律-朱贵_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/093-地藏星-笑面虎-朱富_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/094-地平星-铁胳膊-蔡福_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/095-地损星-一枝花-蔡庆_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/096-地奴星-催命判官-李立_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/097-地察星-青眼虎-李云_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/098-地恶星-没面目-焦挺_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/099-地丑星-石将军-石勇_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/100-地数星-小尉迟-孙新_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/101-地阴星-母大虫-顾大嫂_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/102-地刑星-菜园子-张青_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/103-地壮星-母夜叉-孙二娘_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/104-地劣星-活闪婆-王定六_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/105-地健星-险道神-郁保四_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/106-地耗星-白日鼠-白胜_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/107-地贼星-鼓上蚤-时迁_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        someStrs.append("http://pjgxzvrox.bkt.clouddn.com/108-地狗星-金毛犬-段景住_背面.jpg".addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!)
        return someStrs
    }()
}
